experiment:
    benchmark: 'cifar10-split'
    n_tasks: 5
    model: 'resnet18'
    strategy: 'ewc'
    n_classes: 10
    seed: 42

train:
    optimizer: 'adam'
    loss: 'cross_entropy'
    lr: 0.03

    batch_size: 32
    epochs: 10

strategy:
    ewc_lambda: 1
    
    mem_size: 1000
    batch_size_mem: 32
    patch_size: 28
    stride: 2

run_id: 'ewc_cifar10' 

setup:
    checkpoint_dir: '../checkpoints'
    checkpoint_every: 1 # Create a checkpoint every n epochs: -1 means you checkpoint just at the end of each task
