experiment:
    benchmark: 'cifar100-split'
    n_tasks: 10
    model: 'resnet18'
    strategy: 'naive'
    n_classes: 100

train:
    optimizer: 'adam'
    loss: 'cross_entropy'
    lr: 0.05

    batch_size: 32
    epochs: 50

run_id: 'naive_cifar100'
setup:
    checkpoint_dir: './checkpoints'
    checkpoint_every: 1 # Create a checkpoint every n epochs: -1 means you checkpoint just at the end of each task
