experiment:
    benchmark: 'tinyimagenet-split'
    n_tasks: 10
    model: 'resnet18'
    strategy: 'rrr'
    n_classes: 200

train:
    optimizer: 'adam'
    loss: 'cross_entropy'
    lr: 0.001

    batch_size: 128
    epochs: 100

strategy:
    mem_size: 2000
    mem_adaptive_size: True
    batch_size_mem: 128
    xai_loss: 'l1'
    xai_optimizer: 'adam'
    xai_lr: 0.0005
    xai_regularizer: 100

run_id: 'rrr_tinyimagenet'
setup:
    checkpoint_dir: './checkpoints'
    checkpoint_every: 1 # Create a checkpoint every n epochs: -1 means you checkpoint just at the end of each task
