experiment:
    benchmark: 'cifar10-split'
    n_tasks: 5
    model: 'resnet18'
    strategy: 'rrr'
    n_classes: 10
    seed: 42

train:
    optimizer: 'adam'
    loss: 'cross_entropy'
    lr: 0.03

    batch_size: 32
    epochs: 10

strategy:
    mem_size: 1000
    mem_adaptive_size: True
    batch_size_mem: 32
    xai_loss: 'l1'
    xai_optimizer: 'adam'
    xai_lr: 0.0005
    xai_regularizer: 100
    patch_size: 28
    stride: 2

run_id: 'rrr_cifar10'
setup:
    checkpoint_dir: '../checkpoints'
    checkpoint_every: 1 # Create a checkpoint every n epochs: -1 means you checkpoint just at the end of each task
